Feature/final milestone
LOctavio/Awesome-books pull request #5
Opened 2021-07-08 19:13 UTC by LOctavio

Add navigation bar

2021-07-08 22:26 UTC, voscarmv requested changes
Hi @LOctavio , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- Only a few changes needed regarding the method we use to show/hide content.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Improve your HTML indentation.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 22:26 UTC, voscarmv commented on index.html
> +      </ul>
- [ ] Good use of `display` styles here. But it's preferable to use [Element.classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#examples) to display/hide content. Please use this instead here.

2021-07-08 22:26 UTC, voscarmv commented on index.html
>        <div class="form-group">
- [ ] **[OPTIONAL]** Let's work on our HTML indentation. This is only one place where the indentation of nested HTML tags is unorganized. You may quickly fix your entire HTML document by formatting it with something like Visual Studio Code.

2021-07-09 15:16 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @LOctavio @Gracetemitope🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

![doing good](https://user-images.githubusercontent.com/60631456/125100399-a86b7000-e09e-11eb-8636-13875abebbc9.gif)

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-09 15:17 UTC, merged